apiVersion: apps/v1
kind: service 
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort     
  ports:
    - Ports: 80
      targetPort: 80
      nodePort: 30004
  selector: 
    name: result-app-pod
    app: demo-voting-app