apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: voting-app-pod
    app: demo
spec:
  containers:
    - name: voting-app-pod
      image: kodekloud/examplevotingapp_vote:v1 
      ports:
        - containerPort: 80  